#
# Autogenerated by Thrift Compiler (0.20.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
CurrencyId_Recruits = "Recruit"
CurrencyId_Gold = "Gold"
CurrencyId_Gems = "Gems"
NumDecks = 4
DeckNumSlots = 4
NumChestSlots = 4
