# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish PyPI Test

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools thrift openpyxl
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest
    - name: Build package
      run: python setup.py sdist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.8
      with:
        password: ${{ secrets.TEST_PYPI_XL2THRIFT_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
